Add integration test for error

diff --git a/.github/workflows/integration_tests.yml b/.github/workflows/integration_tests.yml
--- a/.github/workflows/integration_tests.yml
+++ b/.github/workflows/integration_tests.yml
@@ -15,3 +15,23 @@ jobs:
           url: "https://httpbin.org/get"
       - name: Print output
         run: echo "${{ steps.run-action.outputs.response }}"
+
+  test_not_found:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Run action
+        uses: ./
+        id: run-action
+        with: 
+          url: "blah"
+        continue-on-error: true
+      - name: Verify failure
+        if: steps.run-action.outputs.error != ''
+        run: echo "Failed as expected"
+      - name: Unexpected success
+        if: steps.run-action.outputs.error == ''
+        run: echo "Succeeded unexpectedly" && exit 1
+      - name: Print output
+        run: echo "${{ steps.run-action.outputs.error }}"
